Add Extract expression
- Add EXTRACT expression to WalkingSkeleton.usql
- Test fails: E_STORE_USER_FILENOTFOUND: File not found or access denied: C:\Users\matthew\Projects\WeatherData.III\WeatherData.III.AcceptanceTests\bin\Debug\UsqlDataRoot\input\walkingSkeleton\data.txt.
- Create input file and copy to data root
- Test fails: C# error CS0246: The type or namespace name 'WalkingSkeletonExtractor' could not be found (are you missing a using directive or an assembly reference?)